platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: 3.9.9-eclipse-temurin-24

inputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      echo "nameserver 8.8.8.8" > /etc/resolv.conf
      cd repo
      mvn -U -DskipTests package
      # leave artifact in target/ for Dockerfile COPY