platform: linux

image_resource:
  type: docker-image
  source:
    repository: docker
    tag: "24.0.2"

inputs:
  - name: repo

run:
  path: sh
  args:
    - -exc
    - |
      echo "nameserver 8.8.8.8" > /etc/resolv.conf
      # le worker Concourse doit avoir accès au daemon Docker (socket monté)
      docker --version
      docker pull 127.0.0.1:5001/demo:latest
      docker stop demo || true
      docker rm demo || true
      docker run -d --name demo -p 9090:8080 127.0.0.1:5001/demo:latest
