resources:
  - name: repo
    type: git
    source:
      uri: ((github_uri))
      username: ((github_username))
      password: ((github_token))

  - name: docker-image
    type: docker-image
    source:
      repository: ((docker_repository))
      username: ((docker_username))
      password: ((docker_token))

jobs:
  - name: run-tests
    plan:
      - get: repo
        trigger: true
      - task: maven-tests
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.9.9-eclipse-temurin-24
          inputs:
            - name: repo
          caches:
            - path: repo/.m2
          run:
            path: sh
            args:
              - -exc
              - |
                cd repo
                mvn clean test

  - name: build-and-push
    plan:
      - get: repo
        passed: [run-tests]
        trigger: true

      - task: maven-build-and-copy
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: maven
              tag: 3.9.9-eclipse-temurin-24
          inputs:
            - name: repo
          outputs:
            - name: repo
          caches:
            - path: repo/.m2
          run:
            path: sh
            args:
              - -exc
              - |
                cd repo
                mvn clean package
                cp target/demo-0.0.2-SNAPSHOT.jar demo-0.0.2-SNAPSHOT.jar

      - task: generate-tag
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine/git
          inputs:
            - name: repo
          outputs:
            - name: tag-folder
          run:
            path: sh
            args:
              - -exc
              - |
                cd repo
                TAG="$(date +%Y%m%d)-$(git rev-parse --short HEAD)"
                echo "$TAG" > ../tag-folder/tag

      - put: docker-image
        params:
          build: repo
          tag_file: tag-folder/tag